### ISSUE TITLE
doesn't work in game versions lower than 1.16.4

### ISSUE THREAD

**Issue by SanjivanM** [gri573/voxlementary#1]
Title.  Will this shaderpack work in 1.12.2 (modded) with the latest version of Optifine available for that version?

**Comment by gri573** [comment]
no. The latest version of optifine for 1.12.2 is G5, while this shaderpack needs G7 or later to work

**Comment by gri573** [comment]
Voxlementary will not be developed any further, as such, this issue will not be fixed.
