### ISSUE TITLE
Map Textures Broken

### ISSUE THREAD

**Issue by SkeleBones** [gri573/voxlementary#10]
**Describe the bug**
Textures for maps in item frames are broken. 
**How To Reproduce**
1. Use the shaderpack.

**Screenshots**
![image](https://user-images.githubusercontent.com/38815328/132053214-3c224ef9-be05-4b9a-b6ce-670cec531f58.png)

**Fill out:**
 - Optifine version: OptiFine HD U G9
 - Minecraft version: 1.17.1
 - Mods: yes
 - Mac: no
 - GPU: NVIDIA GeForce RTX 3060

**Additional context**

[Y] I have tried if the issue happens with the latest version of Voxlementary.

**Comment by gri573** [comment]
I have occasionally (inconsistently) seen this bug on BSL, so I suspect that it is an optifine issue. I'll close this for now.
