### ISSUE TITLE
gbuffers_water program

### ISSUE THREAD

**Issue by Ronaldvp1106** [gri573/voxlementary#12]
The gbuffers_water is invalid

How To Reproduce

1:Use the shaderpack.

2: Turn on interactive water

3: Look in the bottom left corner

3: Then look at the water (optional, since gbuffers doesn't work)

![image](https://user-images.githubusercontent.com/47673846/138577176-251b16a6-2d4b-4e1a-aa85-2cd6d83a7b8d.png)

**Fill out:**
1.17.1 G7 Optifine
1.17.1 Minecraft Version
 - Mods: no
 - Mac: no
 - GPU: Geforce GTX 1050

Additional Notes:
This seems like a great shader, please fix it.

IMPORTANT: Okay, it's just because of interactive water

[Y] I have tried if the issue happens with the latest version of Voxlementary.

**Comment by gri573** [comment]
Thank you. The issue should be fixed in the latest commit. Please confirm if it is actually fixed so I can close this issue.

**Comment by Ronaldvp1106** [comment]
okay.

**Comment by Ronaldvp1106** [comment]
I will try

**Comment by Ronaldvp1106** [comment]
It works now, thank you so much. Great shaderpack!

**Comment by Ronaldvp1106** [comment]
It works now, thank you so much. Great shaderpack!
