### ISSUE TITLE
Some missing emissives

### ISSUE THREAD

**Issue by Limerance** [gri573/voxlementary#15]
Hiya; saw you had a todo list relatively recent here... I was told this might not be developed any longer, but I figured I'd bring up some things I noticed just in case. I really love just about everything in this but noticed a couple things not properly light-sourcing or emissing.

- Cauldron Lava
- Fire arrows
- Potted plants like the nether shrooms
- Glowing Frames
- Glow lichen (there are some dots on it that another texture pack I was using ended up putting emissions on and it looked really nice, so this would be a nice consideration)
- Diamond blocks might also be a worthwhile consideration to offer as an option, as you have emerald, lapis, and redstone. I feel like it stands out from gold, iron, or coal too much to not be included.

Hopefully I'm not just making a mistake, I've been toying with the shader settings for awhile and ended up preferring your Vanilla+ option over any PBR'd texture packs.

**Comment by gri573** [comment]
integrated PBR will be updated once I switch to the latest complementary version
