### ISSUE TITLE
Mod compatibility.

### ISSUE THREAD

**Issue by ShibeTemple** [gri573/voxlementary#16]
Hello, the colored light effect does not apply to custom blocks. However, it does not default to the BSL shader block light, it simply does not emit light at all.

If this is not a maintained project, could someone point me in the right direction on how to fix this issue? At the minimum, I would want the default BSL shading technique to kick in when the preset block-types aren't found. Thanks!!

**Comment by gri573** [comment]
you can add modded light sources to block.12345 in shaders/block.properties if you want them to emit light, but voxlementary cannot support them natively because it overrides minecraft's lighting rather than augmenting it
