### ISSUE TITLE
Lapis blocklight colors (+ unlit Redstone Ore)

### ISSUE THREAD

**Issue by UnklePhunkle** [gri573/voxlementary#17]
**Describe the bug**
When lapis colors are set to 0 in the blocklight menu, lapis ores give off a yellow-ish light instead. Since unlit redstone ore seems to use the same blocklight, it produces the same effect.

**How To Reproduce**
1. Set LAPIS_COL_R: 0
2. Set LAPIS_COL_G: 0
3. Set LAPIS_COL_B: 0
4. Observe in suitable lighting.

**Screenshots**
With default settings:
![2022-04-29_19 07 27](https://user-images.githubusercontent.com/49177059/166080119-d5ba255b-b565-40fc-813c-0415a3e521b5.jpg)
With [Lapis Colours] set to 0,0,0:
![2022-04-29_19 07 47](https://user-images.githubusercontent.com/49177059/166080123-99b2f7ac-2fb5-455f-a94e-178b7d94ffa9.jpg)
*Solid wall used to divide redstone and lapis.

**Fill out:**
 - Optifine version: HD U H7
 - Minecraft version: 1.18.2 (via Fabric Loader 0.13.3)
 - Mods: Optifabric 1.13.0 / Fabric API 0.51.1+1 / Cloth Config 6.2.57
 - Mac: no
 - GPU: NVIDIA GeForce RTX 2080

**Additional context**
No extra resourcepacks loaded. Voxelementary downloaded same day as screenshots.
[*] I have tried if the issue happens with the latest version of Voxlementary.

**Comment by gri573** [comment]
not entirely fixed, but worked around it in the latest commit
