### ISSUE TITLE
Adding modded lightsource

### ISSUE THREAD

**Issue by Faer97** [gri573/voxlementary#2]
Trying to add modded block into block.properties for the light source doesn't seem to work. I tried adding it under block.11001 -11002 and it doesnt seem to work. How do I add modded blocks as a light source?

**Comment by gri573** [comment]
that is how you are supposed to do it. you may have added them to the 1.12 and below mappings by accident or misspelled the block IDs, I see no other way how that would not work if vanilla light sources do

**Comment by Faer97** [comment]
Found out it was because the modded lightsource is an invisible block. It seems to work with other modded blocks. Thank you
