### ISSUE TITLE
Light sources default to fallback at certain height.

### ISSUE THREAD

**Issue by DankMachine** [gri573/voxlementary#20]
**Bug**
All light sources seem to default to the fallback light color 22 blocks above and below me. This happens even with default settings.

**How To Reproduce**
1. Place light source with custom light (the more it differs from the fallback color, the easier it is to see)
2. Travel at least 22 blocks above or below it (easiest method is to just fly up in creative)

You can also look for a deep Lush Cave and you’ll see the difference in glow berries.

**Video Example**
https://user-images.githubusercontent.com/65761073/169631430-a500d710-0825-4203-b816-dc25f45b02e0.mp4

**Specs**
 - Optifine version: 1.18.2
 - Minecraft version: 1.18.2
 - Mods: No
 - Mac: No
 - GPU: GeForce RTX 2070 Super

[*] I have tried if the issue happens with the latest version of Voxlementary.

**Comment by gri573** [comment]
this is due to the limited voxelisation range of voxlementary, you can set voxel volume height to 192 in shadow settings and increase shadow map resolution to mitigate it
