### ISSUE TITLE
Nether Portal Bug

### ISSUE THREAD

**Issue by gamerbross** [gri573/voxlementary#23]
**Describe the bug**

**How To Reproduce**
1.  Just make a nether portal.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/55158797/185779805-44244c77-841e-41f6-adb2-25a58641f731.png)

**Fill out:**
 - Optifine version: OptiFine_1.19.1_HD_U_H9_pre1
 - Minecraft version: 1.19.1
 - Mods: yes (essential)
 - Mac: no
 - GPU: NVIDIA GeForce RTX 2060

[*] I have tried if the issue happens with the latest version of Voxlementary. (d799a0b338a23268d8548256d4c54b8a002d0ad2)

**Comment by gri573** [comment]
Closing this, as the shader will not be developed further
