### ISSUE TITLE
Lighting Broken, Constant Bright Square Around Player

### ISSUE THREAD

**Issue by xavion251** [gri573/voxlementary#26]
Shader works great and I'd love to use it but unfortunately there is a bright "square" that is always lit super-brightly. It's size seems to correlate to the shadow render distance, but it never goes away completely regardless of what settings I use.

![2023-07-16_03 34 26](https://github.com/gri573/voxlementary/assets/81907303/cefc6e15-0204-4ca1-a3bd-e9a11f66ecb3)

 - Optifine version: Latest version of Rubidium and Oculus
 - Minecraft version: 1.16.5
 - Mods: yes
 - Mac: no
 - GPU: AMD Radeon RX 6600 XT

**Comment by gri573** [comment]
Closing this, as the shader will not be developed further
