### ISSUE TITLE
Some blocks do not emit light?

### ISSUE THREAD

**Issue by MikeTheMotor** [gri573/voxlementary#27]
**Describe the bug**
For example, Frog lights have a weird shadow around them when placed, they do not emit any kind of light even thought without shaders they do. And yes, other light blocks work.

**How To Reproduce**
1. place a frog light.

**Screenshots**
![image](https://github.com/gri573/voxlementary/assets/144274481/e2f66a79-353d-4a50-a935-b40a6e0da4d0)

**Fill out:**
 - Optifine version: Optifine 1.20.1 HD U I5
 - Minecraft version: 1.20.1
 - Mods: no
 - Mac: no
 - GPU: NVIDIA geForce GTX 1060

**Additional context**

[*] I have tried if the issue happens with the latest version of Voxlementary.

**Comment by Quaeft** [comment]
Hi Mike, maybe have a look at [this version of voxlementary](https://github.com/gri573/rethinking-voxels). It is maintained by the original author [gri573](https://github.com/gri573)

**Comment by MikeTheMotor** [comment]
> Hi Mike, maybe have a look at [this version of voxlementary](https://github.com/gri573/rethinking-voxels). It is maintained by the original author [gri573](https://github.com/gri573)

I tried that version and it kept telling me it needed Iris to work?

**Comment by gri573** [comment]
If you download rethinking voxels from [modrinth](https://modrinth.com/shader/rethinking voxels), you can choose the beta series, which still works on optifine

**Comment by gri573** [comment]
If you download rethinking voxels from [modrinth](https://modrinth.com/shader/rethinking-voxels), you can choose the beta version, which is still compatible with optifine

**Comment by gri573** [comment]
Closing this, as the shader will not be developed further
