### ISSUE TITLE
doesn't work on iris

### ISSUE THREAD

**Issue by Furrytime69** [gri573/voxlementary#3]
Lights arent actually lighting, just glowing. could be an optifine issue tho
![2021-07-18_22 02 16](https://user-images.githubusercontent.com/87628580/126096992-16f258db-bc4a-4cfa-8d4a-c93e05786492.png)

**Comment by gri573** [comment]
Are you using a mac? those graphics drivers don't support features that are critical for voxlementary to work (specifically geometry shaders).
it works correctly on my end. sending a screenshot with the F3 debug menu open and a log file would help to identify the issue.

**Comment by vincentchu37** [comment]
I'm guessing this is a thing to do with AMD graphics cards.

![image](https://user-images.githubusercontent.com/19421154/126876330-a104637a-8ba5-483a-b838-b4d807aeaf59.png)

**Comment by gri573** [comment]
it has been reported to me by some other AMD users, turning off fast render may fix it, but the bug reports were inconsistent

**Comment by gri573** [comment]
It will definitely not work on iris for now

**Comment by gri573** [comment]
I confused fast render with render regions, so if you could try with that off it would be appreciated

**Comment by waj171** [comment]
Looks like it's an Iris thing to me

**Comment by Mr-Waterscout** [comment]
Yeah Iris doesn't support voxel-based lighting last I checked

**Comment by tajemniktv** [comment]
> I confused fast render with render regions, so if you could try with that off it would be appreciated

I'm not sure if it was reported, but even with all options from the "Performance" tab turned off, the light still looks like on the screenshots sent before. 

(RX 5700XT, Vanilla+OptiFine pre33) If any more information is needed, let me know

**Comment by MegaCornflakes** [comment]
Having a similar problem here, lights don't actually light up unless I am far away (see screenshot), and they are not colored correctly.
![2021-08-17_20 49 10](https://user-images.githubusercontent.com/31974679/129819141-d586c009-58c5-4384-8b0e-0094058d55d8.png)

**Comment by Reeses-Puffs** [comment]
it might be worth testing this on the custom uniforms branch of Iris

**Comment by gri573** [comment]
It should work now
