### ISSUE TITLE
Dark Daytime Fire on Mobs

### ISSUE THREAD

**Issue by JanTheLynx** [gri573/voxlementary#8]
**Describe the bug**
Whenever a mob catches fire during the day, the fire does not have any emissive lights, but is instead shaded as if it weren't a lighting block. 
 I will note that I have not seen dark fire in the latest version of Complementary.
It looks wrong, and this is a shame because I just LOVE this pack.

**How To Reproduce**
1. Start a world with the time set anywhere from morning to evening. 
2. Light a mob on fire with any method, preferably by spawning an undead mob in the sunlight.
![2021-08-14_22 19 11](https://user-images.githubusercontent.com/31568957/129466073-81bfb83a-7320-4191-b336-58dce63177f4.png)

**Fill out:**
 - Optifine version: HD_U_G9_pre33 (I had this issue in pre32 as well)
 - Minecraft version: 1.17.1
 - Mods: no
 - Mac: no
 - GPU: GeForce RTX 3060 12GB

[*] I have tried if the issue happens with the latest version of Voxlementary.

**Comment by gri573** [comment]
This is a different manifestation of #7

**Comment by Toobzilla** [comment]
would it be possible to add some kind of light to burning mobs? I noticed that they stop being so dark when moving past torches and campfires.

**Comment by pbr4016** [comment]
I hope you will fix this error someday. Voxlementary  is a wonderful shader, but black fire looks strange=(

**Comment by gri573** [comment]
Closing this, as the shader will not be developed further
