### ISSUE TITLE
Skylight broken on some hardwares

### ISSUE THREAD

**Issue by Atrimilan** [gri573/voxlementary#9]
**Describe the bug**

The sun does not light up blocks, but artificial lights does.
I don't know if this is related but when I move away on Y axis from these light sources, they disappear and become as dark as the rest of the world, like a short render distance where the shader work.

I think my issue is similar to the first picture of https://github.com/gri573/voxlementary/issues/7#issue-970747066 but I'm in Vanilla. I tried with & without ressource packs, it doesn't change anything.

> I'm sorry, I don't know much about shaders and how they work, maybe my GPU is not compatible, or there is a button to fix this and I can't find it...
<br>

**How To Reproduce**
1. Dark world : Go somewhere without any artificial light sources
2. Light sources disappearing in the dark : Fly away high/low from light sources
<br>

**Screenshots**
![image](https://user-images.githubusercontent.com/46848005/131223400-7d827667-991a-41dc-801f-666a70a0d5fa.png)
_Example with some builds, time is set to noon_

![image](https://user-images.githubusercontent.com/46848005/131222656-995b12e9-3d65-449d-b041-ba60d3206c99.png)
![image](https://user-images.githubusercontent.com/46848005/131222651-33916d74-3831-46dc-8032-d20a3696e842.png)
_Some light tests_

![image](https://user-images.githubusercontent.com/46848005/131222775-4655efbd-524c-4b89-86f8-fd2f12430aba.png)
_When I start getting too far from light sources (this is not render distance)_

![image](https://user-images.githubusercontent.com/46848005/131223025-159a4abe-2eef-411c-a189-639b4ec29314.png)
_I don't know if this can be useful, but when I move from here, the "shadow" move block by block_
<br>

 - Optifine version: Optifine_1.16.5_HD_U_G8
 - Minecraft version: 1.16.5
 - Mods: no
 - Mac: no
 - GPU: GTX 1060 Max-Q
<br>

**Additional context**
I tried with the shader config of a friend who does not have this bug, and it didn't change anything.
Then I tried multiple configurations even if I don't understand every feature, and nothing has changed either.

[*] I have tried if the issue happens with the latest version of Voxlementary.
<br>

_Thanks in advance, hope this bug report is not useless_

**Comment by gri573** [comment]
Thank you for your detailed bug report. I'm aware of this bug, but apparently the workaround I implemented for it fails on some systems. Development of voxlementary is currently stalling until the next release of complementary because I want to rewrite the whole pipeline. It is currently so prone to breaking in unexpected and weird ways that it isn't enough to fix symptoms of the bigger underlying problems.

**Comment by Atrimilan** [comment]
Okay I see, thank you for your answer,
Good luck, I hope this will be alright to do so.

And gg for what is already made, this is amazing 😄

**Comment by gri573** [comment]
Closing this, as the shader will not be developed further
